import { test, expect } from "@playwright/test";

// TC-014 — Expired reset link is rejected with a clear message
// Traces to: AC-2 / Scenario "Negative — Expired reset link is rejected"
// Generated by the automation-script-generator skill from an approved test case.
// Preconditions: an expired reset link fixture, provisioned by the test setup below.

test.describe("Password reset — expired link", () => {
  test("TC-014: expired reset link is rejected with a clear message", async ({ page }) => {
    // Step 1 — Navigate to the expired reset link
    await page.goto("/reset-password?token=EXPIRED_TOKEN_FIXTURE");

    // Expected: page loads, does not silently redirect to login
    await expect(page).toHaveURL(/reset-password/);

    // Step 2 — Observe the page content
    // Expected: message states the link has expired, offers to request a new one
    await expect(page.getByRole("alert")).toContainText(/expired/i);
    await expect(page.getByRole("button", { name: /request a new link/i })).toBeVisible();

    // Step 3 — Click "request a new link"
    await page.getByRole("button", { name: /request a new link/i }).click();

    // Expected: new link is sent; old link remains invalid
    await expect(page.getByText(/check your email/i)).toBeVisible();
  });
});
